### ISSUE TITLE
Use secretCode of 56 of length

### ISSUE THREAD

**Issue by juliandecoss** [marcelkliemannel/kotlin-onetimepassword#18]
I am trying to use GoogleAuthenticator Class, but the secret i am using has a length of 56, so my otp its not the correct one, is there anyway to make it work?

**Comment by marcelkliemannel** [comment]
You would need to provide a little more context about your problem. It would be best to have a concrete code example or values that are not supposed to work properly.

In general: This library does not limit the length of the secret. Even very long secrets should work. **But**, most generator apps (like the Google's generator app) are limiting the length to a certain length. Which is mostly 10 plain text characters or 16 Base64 characters. Or do not work properly with longer secrets.
